### PR TITLE
Added Esc key functionality to all menus and added exit sound to arena menu

### PR DESCRIPTION
**Pull request by Zed9876**

### CODE REVIEW

**Comment by Zed9876** [comment]
I don't know why so many other commits have been pulled into this list, Something seems wrong, please have a close look before doing anything with this as I have no clue why it's behaving this way.

**Comment by youbitchoc** [comment]
reset the branch to main then cherry-pick f0ea35b70df0f29c6ec3a3ba2acf86f35efe054e

**Comment by 6fears7** [comment]
You'll need to rebase again, sorry

**Comment by henpemaz** [comment]
`Story/StoryOnlineMenu.cs` had a huge refactor, careful not to lose your changes when merging or rebasing. If anything, create a backup of that file first.

**Review by 6fears7 — APPROVED** [review]

**Pull request merged**
