### PR TITLE
Fix some lobby menu bugs

### PR DESCRIPTION
**Pull request by T1mbits**
Synced background to user's chosen submenu to fix my OCD.

Changed LobbyInfoCard to SimplerButtons that immediately allow you to connect and changed the create/join button to a dedicated create button since I removed the lobby create card. This should also fix a bug where if you selected a lobby card but didn't join you wouldn't be able to create a lobby until you reentered the menu because there was no create card to click on.

Still working on a mockup for a full redesign, it's just that I don't think I'll be done before the next release and these were some simple bugs to fix in my previous meddling of the menu. Honestly, there's a high likelihood this broke something else but I didn't notice anything wrong.

### CODE REVIEW

**Comment by T1mbits** [comment]
maybe I'm hallucinating but I could've sworn I removed the create lobby card last time but I guess not. Well, it's gone now and it probably won't cause any problems???

**Comment by 6fears7** [comment]
code looks good. Do you mind posting a video of the changes?

**Comment by T1mbits** [comment]
After thinking about it, I think I'll just keep the lobby create card to minimize confusion, but I'll keep the background fix. Or maybe it's not worth it and I'll just close the PR and just fix everything in the redesign PR

**Comment by 6fears7** [comment]
Just got through testing this. I like it a lot. Do you still want to close this PR / update it or are you good for a merge?

**Comment by T1mbits** [comment]
If you want to merge it then go ahead, I don’t have anything against it as long as it works properly

**Comment by 6fears7** [comment]
Tested, works.

**Pull request merged**
