### PR TITLE
vulture mask sync

### PR DESCRIPTION
**Pull request by 6fears7**
Tested and checked, I think this item falls into the same category as a "rock" in terms of its properties requiring syncing. 

Two player in-game: P1 could grab the mask and wear it, P2 could pull the mask off P1 and wear it. Mask could be dropped. 

As this is my first item to sync I'm not sure if there's usually a 'tell' when it's not working but unless creature in-game behavior has to be synced (which I would think it wouldn't even be handled here), then this is working as I expect, hence my lack of changes.

### CODE REVIEW

**Comment by Chrometurtle** [comment]
Vulture mask requires an online counterpart for it's abstract class. It's not that simple

**Review by Chrometurtle — CHANGES_REQUESTED** [review]
Needs Online counterpart for abstract vulture mask

**Comment by Chrometurtle** [comment]
Observe commit 0ae79ecaf1383084ca26e47319ca0126cd00b78c

**Comment by 6fears7** [comment]
I'm tracking on why it might need an Online counterpart, but then I look at something like[ PlaceObject.Type.Jellyfish](https://github.com/henpemaz/Rain-Meadow/compare/main...sync-story-items#diff-995a3ae1dbbc6cf44db34850736e40ac50d67b163b0418025afc89bba3cc7211R82) or PuffBall and there's no specific  Online counterpart class to speak of aside from existing as a HashSet inside Player Grabbable items, and I'm wondering if 

1. They were just accidentally left out 
or 
2. There weren't any properties about it that required synchronous intervention, which is what seems like is also true for VultureMask.

**Comment by Chrometurtle** [comment]
wrong on both accounts.

Look at the vulture mask code inside rainworld. The abstract counterparts are not simply abstractPhysicalObject

**Comment by 6fears7** [comment]
Ohhhhhh

**Comment by Chrometurtle** [comment]
kk, did a deep dive on abstractVultureMask. The things that would need to be synced only fix graphical issues if we included downpour DLC. For now, no work needs to be done since I have no plans on getting downpour working.

**Pull request closed without merging**
