### PR TITLE
Lobby select overhaul2

### PR DESCRIPTION
**Pull request by 6fears7**
- [x] Password Prompt for client
- [x] "Loading..." notifyDialog when clicking to join
- [ ] Can't confirm yet if the mode filtering works or not

For timbits

### CODE REVIEW

**Comment by 6fears7** [comment]
- [ ] Added pw prompt for client in #555 
- [ ] Loading dialog pops up

Just need testing on this in real world to catch things I'm not thinking about yet.

**Comment by 6fears7** [comment]
@T1mbits please take a look when you are available

**Comment by henpemaz** [comment]
All aboard the LGTM train

**Review by henpemaz — APPROVED** [review]
good stuff

**Pull request merged**
