### PR TITLE
Story: fix start cutscenes

### PR DESCRIPTION
**Pull request by youbitchoc**
fixes hunter host not running start script on respawn
fixes spearmaster client spawning in wrong region

### CODE REVIEW

**Comment by henpemaz** [comment]
Doesn't this cause the fruits on survivor/monk to dupe due to the room fully loading on each client?

**Comment by youbitchoc** [comment]
no, it only affects roomspecificscripts, not actual room loading

**Comment by youbitchoc** [comment]
first client in arti campaign can control fine, beyond that seems to be unable to move?

**Comment by youbitchoc** [comment]
fixed

**Pull request merged**
