### PR TITLE
list needed dlls in CONTRIBUTING.md, fix csproj to use inbuilt copy function

### PR DESCRIPTION
**Pull request by youbitchoc**
fixes postbuild on linux

also the list of dlls might not be the most minimal

### CODE REVIEW

**Comment by 6fears7** [comment]
Thanks for the updated list @youbitchoc 

Please move the necessary DLLs into the CONTRIBUTING.md file. We will want to maintain the README for overview of the mod.

**Comment by youbitchoc** [comment]
shoot, just realized the copy command fix has issues with spaces in filenames

**Comment by youbitchoc** [comment]
should it be formatted as code or as a list?

**Comment by youbitchoc** [comment]
should it be formatted as code or as a list?

**Comment by 6fears7** [comment]
Code. You can convert the list. Thanks

**Comment by henpemaz** [comment]
Good stuff! Thank you

**Pull request merged**
