### PR TITLE
sync weapon thrownBy

### PR DESCRIPTION
**Pull request by youbitchoc**
don't sync tailPos and lastRotation (calculated clientside)

will need to test if this affects creature relations

### CODE REVIEW

**Comment by youbitchoc** [comment]
this should fix friendly fire

**Comment by 6fears7** [comment]
Tested creature relations. Does not address changes alone. Might help with the hook we need though.

**Comment by youbitchoc** [comment]
do we need to sync HitSomethingWithoutStopping for that? or should we sync killtags

**Comment by youbitchoc** [comment]
i think we can deal with creature relations in another pr, this one is more for fixing friendly fire

**Comment by 6fears7** [comment]
oh yeah creature relations is gonna be a bear. Outside this PR scope

LGTM

**Pull request merged**
