### PR TITLE
BanHammer: kick to lobby select, not main menu

### PR DESCRIPTION
**Pull request by youbitchoc**
don't call ExitToMenu, may break in arena mode

### CODE REVIEW

**Comment by 6fears7** [comment]
Can't decompile atm, can you expand your statement? Why would ExitToMenu break arena?

**Comment by youbitchoc** [comment]
arena exits to multiplayermenu rather than mainmenu

**Comment by youbitchoc** [comment]
banned player gets stuck trying to release resources and blackscreens, not sure why

**Comment by henpemaz** [comment]
If you're kicking someone from the lobby, they shouldn't be allowed to stay on the lobby.

Did you mean lobbyselect?

That lobbymenu that you modified is the abandoned menu for FreeRoam.

The infinite load is because in a hook to rainworldgame.shutdownprocess we specifically check for the next process in order to decide whether to spinlock the resource release or not.

**Comment by youbitchoc** [comment]
ah. whoops.

**Comment by youbitchoc** [comment]
might be better to just redo this

**Pull request closed without merging**
