### PR TITLE
check if WorldSession owned, drop changedRegions

### PR DESCRIPTION
**Pull request by youbitchoc**
more robust fix for clients joining in the wrong region

needs testing

### CODE REVIEW

**Comment by youbitchoc** [comment]
game logic for determining spawn region is very ugly and very hard to reuse for this (it loads the world)

**Comment by 6fears7** [comment]
Think this has been addressed in a new build but will wait  for confirm.

**Comment by youbitchoc** [comment]
? which commit/pr?

**Comment by 6fears7** [comment]
Could've sworn you dropped a build for enabling clients to join after crossing karma gate and then denning.

**Comment by youbitchoc** [comment]
better solution might be to spawn the player in then abort if the worldsession is different

**Pull request closed without merging**
