### PR TITLE
Add slug icons

### PR DESCRIPTION
**Pull request by 6fears7**
WIP: 
- ~~Icons appear in-game, but players who join are not adding in-game players to their list.~~
- I think they are being added for clients but everyone's occupying the same position. Need to make current user the first index.
- Spacing is a little too far between each other at the moment.

Below is host perspective. 

icons

### CODE REVIEW

**Comment by 6fears7** [comment]
image


Considering making the icon move across a fixed y-axis. 

Reasons:

1. It allows users to find a dead slugcat more easily, especially in the event two players look similar.
2. Because the HUD is off unless the remix option button is pressed, the "cleanliness" of the fixed icon look that Jolly captured is marginally irrelevant since the usefulness of being in a larger space than Jolly demands a more appropriate method of finding your friends and knowing their status.

**Comment by 6fears7** [comment]
Adjusted placement 

image


image

On death, makes 50% transparency and death icon.

May look into dynamically moving the image similar to username and arrow when player is outside room but will see

**Comment by 6fears7** [comment]
https://github.com/henpemaz/Rain-Meadow/assets/57415489/194b797c-26fe-482a-a552-69a5bb45dbd6

Current implementation. Need to test on-death icon swap and then should be g2g.

**Comment by 6fears7** [comment]
This is ready to go.

- added color correction for players choosing funky body color 
- confirmed death icon works as expected 

First image will not show the correction since it was an earlier screenshot 

Death icon update: 
image


Color correction:
image

**Comment by Chrometurtle** [comment]
> @Chrometurtle let me know if you want me to explore fixing gates adding icons in this PR or if you want it separately pulled

Seperate PR sounds good.

**Comment by 6fears7** [comment]
image


@Chrometurtle This is what the final product will look like. A subtle shift of the arrow. I am not going to pursue variably changing the translation based on player steam character length due to potential obscuring issues arising where players with short names hide the shortcolor entrance color.

**Review by Chrometurtle — APPROVED** [review]
lgtm

**Pull request merged**
